### ISSUE TITLE
generate.py Memory Growth

### ISSUE THREAD

**Issue by Sonophoto** [Sonophoto/skunkdb#5]
When generating database records, generate.py is building the entire table in memory before writing it out to disk.

**Comment by danielrmeyer** [comment]
If you want minimal memory pressure then simply insert values one at a time rather than use executemany.  Building the data in memory and inserting with executemany will probably be faster.  To achieve a balance with large input that does not fit in memory go ahead and chunk the input and do a series calls to executemany with each input chunk.  If this level of control is desired I would add an option to accept a variable chunk size.

**Comment by Sonophoto** [comment]
lulz.

**Comment by Sonophoto** [comment]
silly jackass.
